name: Terraform code checks

inputs:
  aws_account_id:
    description: 'AWS account id'
    required: true
  aws_region:
    description: 'AWS region'
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/chrispsheehan-lambda-express-api-gha-validate-role
        role-session-name: GitHubActions

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: terraform format
      shell: bash
      run: |
        cd tf
        terraform fmt -diff -recursive -check

    - name: init
      shell: bash
      run: |
        cd tf
        terraform init

    - name: validate
      shell: bash
      run: |
        cd tf
        terraform validate
