name: Terraform code checks

inputs:
  aws_account_id:
    description: 'AWS account id'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
  aws_role:
    description: 'AWS role to assume'
    required: true
  terraform_action:
    description: 'Terraform action to preform either apply/destroy'
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.aws_role }}
        role-session-name: GitHubActions

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Init
      shell: bash
      run: |
        cd tf
        terraform init

    - name: Action
      shell: bash
      run: |
        cd tf
        terraform ${{ inputs.terraform_action }} -auto-approve
