name: Deploy Dev

on:
    workflow_dispatch:
    push:
        branches: main

env:
    app_folder: src
    app_zip_path: lambda-express-api.zip

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
          cloudfront_distribution_id: ${{ steps.apply.outputs.DISTRIBUTION_ID }}
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
    
          - name: Build
            run: |
                cd ${{ env.app_folder }}
                npm install
    
          - name: Zip
            run: |
                zip -r ${{ env.app_zip_path }} ${{ env.app_folder }}
    
          - name: Upload build artefact
            uses: actions/upload-artifact@v3
            with:
                name: zipped-code
                path: ${{ env.app_zip_path }}

    dev:
        runs-on: ubuntu-latest
        steps:
          - name: Download a single artifact
            uses: actions/download-artifact@v3
            with:
                name: zipped-code
          - name: debug
            run: ls -r
      

        # permissions:
        #     id-token: write
        #     contents: read
        # uses: ./.github/workflows/apply-infra.yml
        # with:
        #     stage: dev

    # get-url:
    #     needs: dev
    #     runs-on: ubuntu-latest
    #     steps:
    #         - run: echo random-number ${{ steps.action.outputs.api-url }}
    #           shell: bash
