name: Deploy Dev

on:
    workflow_dispatch:
    push:
        branches: main

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/deploy.yml
    with:
      stage: dev
