name: Deploy Dev

on:
    workflow_dispatch:
    push:
        branches: main

jobs:
    dev:
        permissions:
            id-token: write
            contents: read
        uses: ./.github/workflows/deploy-environment.yml
        with:
            stage: dev
