name: Deploy Dev

on:
    workflow_dispatch:
    push:
        branches: main

permissions:
    id-token: write
    contents: read

env:
    aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
    aws_region: ${{ vars.AWS_REGION }}
    aws_role: ${{ vars.AWS_ROLE_VALIDATE_ONLY }}

jobs:
    dev:
        uses: ./.github/workflows/deploy-environment.yml
        with:
            stage: dev

    dev-kill:
        needs: dev
        uses: ./.github/workflows/destroy-environment.yml
        with:
            stage: dev
