name: Deploy Tag to QA

on:
    push:
        tags:
        - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
    id-token: write
    contents: read

env:
    aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
    aws_region: ${{ vars.AWS_REGION }}
    aws_role: ${{ vars.AWS_ROLE }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Build and upload
            uses: ./.github/actions/build
            with:
                aws_account_id: ${{ env.aws_account_id }}
                aws_region: ${{ env.aws_region }}
                aws_role: ${{ env.aws_role }}
                version_file: ${{  github.ref_name }}.zip

    qa:
        needs:
            - build
        uses: ./.github/workflows/deploy.yml
        with:
            stage: qa
            version_file: ${{ github.ref_name }}.zip
