name: Deploy Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
  aws_region: ${{ vars.AWS_REGION }}
  aws_role: chrispsheehan-lambda-express-api-gha-deploy-branch-role

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.aws_region }}
          role-to-assume: arn:aws:iam::${{ env.aws_account_id }}:role/${{ env.aws_role }}
          role-session-name: GitHubActions

      - name: Init
        run: |
            cd tf
            terraform init

      - name: Validate
        run: |
            cd tf
            terraform validate

      - name: Apply
        id: apply
        run: |
            cd tf
            terraform apply -auto-approve

      - name: destroy
        id: destroy
        run: |
            cd tf
            terraform destroy -auto-approve
