name: Destroy Environment

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Environment to destroy
        options: 
        - dev
        - qa
      message:
        required: true

env:
  aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
  aws_region: ${{ vars.AWS_REGION }}
  aws_role: ${{ vars.AWS_ROLE }}

permissions:
  id-token: write
  contents: read

jobs:  
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Terraform Destroy
        uses: ./.github/actions/terraform_action
        with:
          aws_account_id: ${{ env.aws_account_id }}
          aws_region: ${{ env.aws_region }}
          aws_role: ${{ env.aws_role }}
          terraform_action: destroy
          stage: ${{ inputs.stage }}